# Generated by Django 4.2 on 2023-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
