# Generated by Django 4.2 on 2023-05-31 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
